/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginSsoRouteImport } from './routes/login.sso'
import { Route as LoginPasswordRouteImport } from './routes/login.password'
import { Route as AuthValidateRouteImport } from './routes/_auth.validate'
import { Route as AuthLeaderboardRouteImport } from './routes/_auth.leaderboard'
import { Route as AuthHomeRouteImport } from './routes/_auth.home'
import { Route as AuthQuestDetailsQuestIdRouteImport } from './routes/_auth.quest-details.$questId'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSsoRoute = LoginSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => LoginRoute,
} as any)
const LoginPasswordRoute = LoginPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => LoginRoute,
} as any)
const AuthValidateRoute = AuthValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLeaderboardRoute = AuthLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuestDetailsQuestIdRoute = AuthQuestDetailsQuestIdRouteImport.update({
  id: '/quest-details/$questId',
  path: '/quest-details/$questId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/rules': typeof RulesRoute
  '/home': typeof AuthHomeRoute
  '/leaderboard': typeof AuthLeaderboardRoute
  '/validate': typeof AuthValidateRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/sso': typeof LoginSsoRoute
  '/quest-details/$questId': typeof AuthQuestDetailsQuestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/rules': typeof RulesRoute
  '/home': typeof AuthHomeRoute
  '/leaderboard': typeof AuthLeaderboardRoute
  '/validate': typeof AuthValidateRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/sso': typeof LoginSsoRoute
  '/quest-details/$questId': typeof AuthQuestDetailsQuestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/rules': typeof RulesRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/leaderboard': typeof AuthLeaderboardRoute
  '/_auth/validate': typeof AuthValidateRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/sso': typeof LoginSsoRoute
  '/_auth/quest-details/$questId': typeof AuthQuestDetailsQuestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/rules'
    | '/home'
    | '/leaderboard'
    | '/validate'
    | '/login/password'
    | '/login/sso'
    | '/quest-details/$questId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/rules'
    | '/home'
    | '/leaderboard'
    | '/validate'
    | '/login/password'
    | '/login/sso'
    | '/quest-details/$questId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/rules'
    | '/_auth/home'
    | '/_auth/leaderboard'
    | '/_auth/validate'
    | '/login/password'
    | '/login/sso'
    | '/_auth/quest-details/$questId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/sso': {
      id: '/login/sso'
      path: '/sso'
      fullPath: '/login/sso'
      preLoaderRoute: typeof LoginSsoRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/password': {
      id: '/login/password'
      path: '/password'
      fullPath: '/login/password'
      preLoaderRoute: typeof LoginPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_auth/validate': {
      id: '/_auth/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof AuthValidateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/leaderboard': {
      id: '/_auth/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthLeaderboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quest-details/$questId': {
      id: '/_auth/quest-details/$questId'
      path: '/quest-details/$questId'
      fullPath: '/quest-details/$questId'
      preLoaderRoute: typeof AuthQuestDetailsQuestIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthHomeRoute: typeof AuthHomeRoute
  AuthLeaderboardRoute: typeof AuthLeaderboardRoute
  AuthValidateRoute: typeof AuthValidateRoute
  AuthQuestDetailsQuestIdRoute: typeof AuthQuestDetailsQuestIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHomeRoute: AuthHomeRoute,
  AuthLeaderboardRoute: AuthLeaderboardRoute,
  AuthValidateRoute: AuthValidateRoute,
  AuthQuestDetailsQuestIdRoute: AuthQuestDetailsQuestIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LoginRouteChildren {
  LoginPasswordRoute: typeof LoginPasswordRoute
  LoginSsoRoute: typeof LoginSsoRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginPasswordRoute: LoginPasswordRoute,
  LoginSsoRoute: LoginSsoRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
